name: CD Dale.gg

on:
  push:
    branches:
      - master

env:
  PREFIX: dalegg
  REGISTRY_REPO: jlenon7/dalegg
  DEPLOY_CONF: deployment/dalegg
  K8S_CLUSTER: duogg-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        NPM_AUTH_PKG: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: jlenon7/dalegg
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: NPM_AUTH_PKG

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Save AWS Kubeconfig
      run: aws eks --region us-east-1 update-kubeconfig --name $K8S_CLUSTER

    - name: Export KUBECONFIG
      run: export KUBECONFIG=~/.kube/config

    - name: Deploy to AWS Kubernetes
      run: kubectl set image $DEPLOY_CONF $PREFIX=$REGISTRY_REPO

    - name: Verify deployment
      run: kubectl rollout status $DEPLOY_CONF




